<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- body defining macro -->
  <xacro:macro name="body" params="wheel_diameter">

    <link name="base_link"></link> 

    <link name="body_link">
      <visual>
        <geometry>
          <mesh filename="file://$(find rosbot_description)/models/rosbot_base/meshes/body.dae" scale="0.001 0.001 0.001"/>
        </geometry>
        <origin xyz="0.0 0.0 -0.02" rpy="${pi/2} 0.0 ${pi/2}"/>
      </visual>

      <collision>
        <geometry>
          <box size="0.197 0.150 0.080" />
        </geometry>
        <origin xyz="0.0 0.0 ${0.040-0.02}" rpy="0.0 0.0 0.0"/>
      </collision>

      <inertial>
          <mass value="5.0" />
          <inertia ixx="0.0025" ixy="0.000"  ixz="0.000"
                               iyy="0.0025"  iyz="0.000"
                                            izz="0.0025" />
      </inertial>
    </link>

    <link name="cover_link">
      <visual>
        <geometry>
          <mesh filename="file://$(find rosbot_description)/models/rosbot_base/meshes/cover.dae" scale="0.001 0.001 0.001"/>
        </geometry>
        <origin xyz="0.0 0.0 -0.002" rpy="${pi/2} 0.0 ${pi/2}"/>
      </visual>

      <inertial>
        <mass value="0.000001" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                           iyy="1.0" iyz="0.0"
                                     izz="0.0" />
      </inertial>
    </link> 

    <link name="imu_link">
      <inertial>
        <mass value="0.001" />
        <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
      </inertial>
    </link>

    <link name="camera_link">
      <inertial>
        <mass value="0.000001" />
        <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
      </inertial>
    </link>

    <joint name="base_link_to_body_joint" type="fixed">
      <origin xyz="0.0 0.0 ${wheel_diameter/2}" rpy="0.0 0.0 0.0" />
      <parent link="base_link" />
      <child link="body_link" />
    </joint>

    <joint name="body_to_cover_joint" type="fixed">
      <origin xyz="0.0 0.0 0.060" rpy="0.0 0.0 0.0" />
      <parent link="body_link" />
      <child link="cover_link" />
    </joint>

    <joint name="body_link_to_imu_link_joint" type="fixed">
      <origin xyz="-0.1369 -0.0419 0.0370" rpy="0.0 0.0 0.0" />
      <parent link="body_link" />
      <child link="imu_link" />
    </joint>

    <joint name="body_link_to_camera_link_joint" type="fixed">
      <origin xyz="-0.0141 0.0 0.125" rpy="0.0 0.0 0.0" />
      <parent link="body_link" />
      <child link="camera_link" />
    </joint>

    <gazebo reference="body_link">
      <material>Gazebo/White</material>
    </gazebo>

    <gazebo reference="cover_link">
      <material>Gazebo/Red</material>
    </gazebo>

  
  </xacro:macro>

</robot>

